"""Initial procurement schema, frozen at release 1."""

from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None


def upgrade():
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scoring_settings",
        sa.Column("price_weight", sa.Integer(), nullable=False),
        sa.Column("lead_time_weight", sa.Integer(), nullable=False),
        sa.Column("reliability_weight", sa.Integer(), nullable=False),
        sa.Column("fit_weight", sa.Integer(), nullable=False),
        sa.Column("anomaly_threshold", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("lead_time_behavior", sa.String(), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id"),
    )
    op.create_index(op.f("ix_scoring_settings_organization_id"), "scoring_settings", ["organization_id"], unique=False)
    op.create_table(
        "suppliers",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("aliases", sa.JSON(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("email_domain", sa.String(), nullable=False),
        sa.Column("website", sa.String(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("payment_terms", sa.String(), nullable=False),
        sa.Column("preferred_supplier", sa.Boolean(), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_suppliers_organization_id"), "suppliers", ["organization_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column("old_value", sa.JSON(), nullable=True),
        sa.Column("new_value", sa.JSON(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(op.f("ix_audit_events_organization_id"), "audit_events", ["organization_id"], unique=False)
    op.create_table(
        "auth_sessions",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_auth_sessions_organization_id"), "auth_sessions", ["organization_id"], unique=False)
    op.create_table(
        "items",
        sa.Column("sku", sa.String(), nullable=False),
        sa.Column("manufacturer_part_number", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("uom", sa.String(), nullable=False),
        sa.Column("preferred_supplier_id", sa.String(length=36), nullable=True),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["preferred_supplier_id"],
            ["suppliers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "sku"),
    )
    op.create_index(op.f("ix_items_organization_id"), "items", ["organization_id"], unique=False)
    op.create_table(
        "rfqs",
        sa.Column("number", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("required_delivery", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("supplier_count", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "number"),
    )
    op.create_index(op.f("ix_rfqs_organization_id"), "rfqs", ["organization_id"], unique=False)
    op.create_table(
        "supplier_contacts",
        sa.Column("supplier_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_supplier_contacts_organization_id"), "supplier_contacts", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_supplier_contacts_supplier_id"), "supplier_contacts", ["supplier_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("storage_key", sa.String(), nullable=False),
        sa.Column("mime_type", sa.String(), nullable=False),
        sa.Column("sha256", sa.String(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("stage", sa.String(), nullable=False),
        sa.Column("classification", sa.String(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("rfq_id", sa.String(length=36), nullable=True),
        sa.Column("uploaded_by", sa.String(length=36), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rfq_id"],
            ["rfqs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "sha256"),
    )
    op.create_index(op.f("ix_documents_organization_id"), "documents", ["organization_id"], unique=False)
    op.create_index(op.f("ix_documents_rfq_id"), "documents", ["rfq_id"], unique=False)
    op.create_table(
        "item_aliases",
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("alias", sa.String(), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_item_aliases_organization_id"), "item_aliases", ["organization_id"], unique=False)
    op.create_table(
        "purchase_history",
        sa.Column("po_number", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("supplier_id", sa.String(length=36), nullable=False),
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("uom", sa.String(), nullable=False),
        sa.Column("lead_time_days", sa.Integer(), nullable=False),
        sa.Column("expected_delivery", sa.Date(), nullable=False),
        sa.Column("actual_delivery", sa.Date(), nullable=True),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "po_number", "item_id"),
    )
    op.create_index(op.f("ix_purchase_history_date"), "purchase_history", ["date"], unique=False)
    op.create_index(op.f("ix_purchase_history_item_id"), "purchase_history", ["item_id"], unique=False)
    op.create_index(op.f("ix_purchase_history_organization_id"), "purchase_history", ["organization_id"], unique=False)
    op.create_index(op.f("ix_purchase_history_supplier_id"), "purchase_history", ["supplier_id"], unique=False)
    op.create_table(
        "rfq_items",
        sa.Column("rfq_id", sa.String(length=36), nullable=False),
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rfq_id"],
            ["rfqs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rfq_items_organization_id"), "rfq_items", ["organization_id"], unique=False)
    op.create_index(op.f("ix_rfq_items_rfq_id"), "rfq_items", ["rfq_id"], unique=False)
    op.create_table(
        "supplier_item_mappings",
        sa.Column("supplier_id", sa.String(length=36), nullable=False),
        sa.Column("supplier_sku", sa.String(), nullable=False),
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("confirmed_by", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["confirmed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "supplier_id", "supplier_sku"),
    )
    op.create_index(
        op.f("ix_supplier_item_mappings_organization_id"), "supplier_item_mappings", ["organization_id"], unique=False
    )
    op.create_table(
        "document_extractions",
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_document_extractions_document_id"), "document_extractions", ["document_id"], unique=False)
    op.create_index(
        op.f("ix_document_extractions_organization_id"), "document_extractions", ["organization_id"], unique=False
    )
    op.create_table(
        "quotes",
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("rfq_id", sa.String(length=36), nullable=True),
        sa.Column("supplier_id", sa.String(length=36), nullable=True),
        sa.Column("supplier_name", sa.String(), nullable=False),
        sa.Column("supplier_email", sa.String(), nullable=True),
        sa.Column("quote_number", sa.String(), nullable=False),
        sa.Column("rfq_number", sa.String(), nullable=True),
        sa.Column("quote_date", sa.Date(), nullable=True),
        sa.Column("expiration_date", sa.Date(), nullable=True),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("payment_terms", sa.String(), nullable=True),
        sa.Column("shipping_terms", sa.String(), nullable=True),
        sa.Column("shipping_cost", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("tax", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("stated_subtotal", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("stated_total", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("source_references", sa.JSON(), nullable=False),
        sa.Column("review_status", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rfq_id"],
            ["rfqs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id"),
    )
    op.create_index(op.f("ix_quotes_organization_id"), "quotes", ["organization_id"], unique=False)
    op.create_index(op.f("ix_quotes_rfq_id"), "quotes", ["rfq_id"], unique=False)
    op.create_index(op.f("ix_quotes_supplier_id"), "quotes", ["supplier_id"], unique=False)
    op.create_table(
        "alerts",
        sa.Column("quote_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["quotes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alerts_organization_id"), "alerts", ["organization_id"], unique=False)
    op.create_index(op.f("ix_alerts_quote_id"), "alerts", ["quote_id"], unique=False)
    op.create_table(
        "email_drafts",
        sa.Column("quote_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["quotes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_email_drafts_organization_id"), "email_drafts", ["organization_id"], unique=False)
    op.create_table(
        "field_corrections",
        sa.Column("quote_id", sa.String(length=36), nullable=False),
        sa.Column("field", sa.String(), nullable=False),
        sa.Column("original_value", sa.JSON(), nullable=False),
        sa.Column("corrected_value", sa.JSON(), nullable=False),
        sa.Column("corrected_by", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["corrected_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["quotes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_field_corrections_organization_id"), "field_corrections", ["organization_id"], unique=False
    )
    op.create_table(
        "quote_items",
        sa.Column("quote_id", sa.String(length=36), nullable=False),
        sa.Column("item_id", sa.String(length=36), nullable=True),
        sa.Column("supplier_sku", sa.String(), nullable=False),
        sa.Column("manufacturer_part_number", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("uom", sa.String(), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("moq", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("lead_time_days", sa.Integer(), nullable=True),
        sa.Column("lead_time_min", sa.Integer(), nullable=True),
        sa.Column("delivery_date", sa.Date(), nullable=True),
        sa.Column("stated_line_total", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("match_method", sa.String(), nullable=False),
        sa.Column("source_references", sa.JSON(), nullable=False),
        sa.Column("price_tiers", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["quotes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quote_items_organization_id"), "quote_items", ["organization_id"], unique=False)
    op.create_index(op.f("ix_quote_items_quote_id"), "quote_items", ["quote_id"], unique=False)
    op.create_table(
        "recommendations",
        sa.Column("rfq_id", sa.String(length=36), nullable=False),
        sa.Column("quote_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["quotes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rfq_id"],
            ["rfqs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recommendations_organization_id"), "recommendations", ["organization_id"], unique=False)
    op.create_index(op.f("ix_recommendations_rfq_id"), "recommendations", ["rfq_id"], unique=False)
    op.create_table(
        "approvals",
        sa.Column("recommendation_id", sa.String(length=36), nullable=False),
        sa.Column("approved_by", sa.String(length=36), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recommendation_id"),
    )
    op.create_index(op.f("ix_approvals_organization_id"), "approvals", ["organization_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_approvals_organization_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_recommendations_rfq_id"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_organization_id"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_quote_items_quote_id"), table_name="quote_items")
    op.drop_index(op.f("ix_quote_items_organization_id"), table_name="quote_items")
    op.drop_table("quote_items")
    op.drop_index(op.f("ix_field_corrections_organization_id"), table_name="field_corrections")
    op.drop_table("field_corrections")
    op.drop_index(op.f("ix_email_drafts_organization_id"), table_name="email_drafts")
    op.drop_table("email_drafts")
    op.drop_index(op.f("ix_alerts_quote_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_organization_id"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_quotes_supplier_id"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_rfq_id"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_organization_id"), table_name="quotes")
    op.drop_table("quotes")
    op.drop_index(op.f("ix_document_extractions_organization_id"), table_name="document_extractions")
    op.drop_index(op.f("ix_document_extractions_document_id"), table_name="document_extractions")
    op.drop_table("document_extractions")
    op.drop_index(op.f("ix_supplier_item_mappings_organization_id"), table_name="supplier_item_mappings")
    op.drop_table("supplier_item_mappings")
    op.drop_index(op.f("ix_rfq_items_rfq_id"), table_name="rfq_items")
    op.drop_index(op.f("ix_rfq_items_organization_id"), table_name="rfq_items")
    op.drop_table("rfq_items")
    op.drop_index(op.f("ix_purchase_history_supplier_id"), table_name="purchase_history")
    op.drop_index(op.f("ix_purchase_history_organization_id"), table_name="purchase_history")
    op.drop_index(op.f("ix_purchase_history_item_id"), table_name="purchase_history")
    op.drop_index(op.f("ix_purchase_history_date"), table_name="purchase_history")
    op.drop_table("purchase_history")
    op.drop_index(op.f("ix_item_aliases_organization_id"), table_name="item_aliases")
    op.drop_table("item_aliases")
    op.drop_index(op.f("ix_documents_rfq_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_organization_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_supplier_contacts_supplier_id"), table_name="supplier_contacts")
    op.drop_index(op.f("ix_supplier_contacts_organization_id"), table_name="supplier_contacts")
    op.drop_table("supplier_contacts")
    op.drop_index(op.f("ix_rfqs_organization_id"), table_name="rfqs")
    op.drop_table("rfqs")
    op.drop_index(op.f("ix_items_organization_id"), table_name="items")
    op.drop_table("items")
    op.drop_index(op.f("ix_auth_sessions_organization_id"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index(op.f("ix_audit_events_organization_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_suppliers_organization_id"), table_name="suppliers")
    op.drop_table("suppliers")
    op.drop_index(op.f("ix_scoring_settings_organization_id"), table_name="scoring_settings")
    op.drop_table("scoring_settings")
    op.drop_table("organizations")
    # ### end Alembic commands ###
